version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:2.7.18
    steps:
      - run:
          name: lint code
          command: |
            pip install pip==20.3.3
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test_local_docker:
    working_directory: ~/ckanext-datajson
    machine: true
    environment:
      COMPOSE_FILE: docker-compose.legacy.yml
    steps:
      - checkout
      - run:
          name: Start CKAN
          command: |
            make build
            docker-compose -f $COMPOSE_FILE up
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 2m
      - run:
          name: Test extension
          command: |
            docker-compose -f $COMPOSE_FILE logs db
            docker-compose -f $COMPOSE_FILE logs ckan
            make test-legacy

  build_ckan_28:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run:
          name: install and test
          command: bin/travis-build-2.8.bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build_gsa_ckan_inventory_next:
          requires:
              - lint
      - test_local_docker:
          requires:
            - lint
      - build_ckan_28:
          requires:
            - lint
